// StatsTracker.swift — Slap statistics and fun counters
// OpenSlap – macOS accelerometer-based slap detection
//
// Tracks session and lifetime slap stats. Persisted to UserDefaults.

import Foundation
import Combine

final class StatsTracker: ObservableObject {

    // MARK: - Published Stats

    /// Total slaps detected this session (since app launch).
    @Published private(set) var sessionCount: Int = 0

    /// Total slaps detected across all sessions.
    @Published private(set) var lifetimeCount: Int = 0

    /// Hardest slap ever recorded (in g-force).
    @Published private(set) var peakForceEver: Double = 0

    /// Hardest slap this session.
    @Published private(set) var peakForceSession: Double = 0

    /// Average slap force this session.
    @Published private(set) var averageForceSession: Double = 0

    /// Timestamp of the first ever slap.
    @Published private(set) var firstSlapDate: Date?

    /// Current slaps-per-minute rate (rolling 1-minute window).
    @Published private(set) var currentRate: Double = 0

    // MARK: - Internal State

    private var sessionForces: [Double] = []
    private var recentTimestamps: [Date] = []
    private var rateTimer: Timer?

    init() {
        loadLifetimeStats()
        startRateTimer()
    }

    // MARK: - Recording

    /// Record a new slap event.
    func recordSlap(force: Double) {
        let now = Date()

        sessionCount += 1
        lifetimeCount += 1
        sessionForces.append(force)
        recentTimestamps.append(now)

        if force > peakForceSession {
            peakForceSession = force
        }
        if force > peakForceEver {
            peakForceEver = force
        }

        averageForceSession = sessionForces.reduce(0, +) / Double(sessionForces.count)

        if firstSlapDate == nil {
            firstSlapDate = now
        }

        saveLifetimeStats()
    }

    /// Reset session stats (on app relaunch).
    func resetSession() {
        sessionCount = 0
        peakForceSession = 0
        averageForceSession = 0
        sessionForces.removeAll()
        recentTimestamps.removeAll()
    }

    /// Reset all stats (user action).
    func resetAll() {
        resetSession()
        lifetimeCount = 0
        peakForceEver = 0
        firstSlapDate = nil
        saveLifetimeStats()
    }

    // MARK: - Fun Stats

    /// A fun description of the user's slapping habits.
    var slapperTitle: String {
        switch lifetimeCount {
        case 0:        return "Pacifist"
        case 1...10:   return "Curious Tapper"
        case 11...50:  return "Slap Apprentice"
        case 51...200: return "Certified Slapper"
        case 201...500: return "Slap Enthusiast"
        case 501...1000: return "Professional Slapper"
        case 1001...5000: return "Slap Master"
        default:       return "Laptop Abuse Specialist"
        }
    }

    /// Estimated total energy delivered to the laptop (very approximate, for fun).
    /// Assumes ~0.5 kg effective mass and converts g-force to joules.
    var estimatedEnergyJoules: Double {
        let totalForceG = sessionForces.reduce(0, +)
        // E ≈ 0.5 * m * v², approximating v from impulse
        // This is wildly inaccurate but fun to show
        return totalForceG * 9.81 * 0.001 // Rough order of magnitude
    }

    /// Export stats as a formatted string for sharing.
    func exportStats() -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium

        var lines = [
            "OpenSlap Stats Export",
            "═══════════════════════",
            "",
            "Title: \(slapperTitle)",
            "Lifetime slaps: \(lifetimeCount)",
            "Session slaps: \(sessionCount)",
            "Peak force (ever): \(String(format: "%.1f", peakForceEver))g",
            "Peak force (session): \(String(format: "%.1f", peakForceSession))g",
            "Average force: \(String(format: "%.1f", averageForceSession))g",
        ]
        if let firstDate = firstSlapDate {
            lines.append("Slapping since: \(dateFormatter.string(from: firstDate))")
        }
        lines.append("")
        lines.append("Generated by OpenSlap — don't break your expensive laptop!")
        return lines.joined(separator: "\n")
    }

    // MARK: - Persistence

    private func saveLifetimeStats() {
        let defaults = UserDefaults.standard
        defaults.set(lifetimeCount, forKey: "stats.lifetimeCount")
        defaults.set(peakForceEver, forKey: "stats.peakForceEver")
        if let firstDate = firstSlapDate {
            defaults.set(firstDate, forKey: "stats.firstSlapDate")
        }
    }

    private func loadLifetimeStats() {
        let defaults = UserDefaults.standard
        lifetimeCount = defaults.integer(forKey: "stats.lifetimeCount")
        peakForceEver = defaults.double(forKey: "stats.peakForceEver")
        firstSlapDate = defaults.object(forKey: "stats.firstSlapDate") as? Date
    }

    // MARK: - Rate Calculation

    private func startRateTimer() {
        // Update the slaps-per-minute rate every second
        rateTimer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { [weak self] _ in
            self?.updateRate()
        }
    }

    private func updateRate() {
        let now = Date()
        // Keep only the last 60 seconds of timestamps
        recentTimestamps.removeAll { now.timeIntervalSince($0) > 60 }
        currentRate = Double(recentTimestamps.count) // slaps in last minute
    }
}
